[package]
name = "francium_pc_bootimg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = { git = "https://github.com/rust-osdev/bootloader.git" }
